# Install the pre-commit hooks below with
# 'pre-commit install'

# Auto-update the version of the hooks with
# 'pre-commit autoupdate'

# Run the hooks on all files with
# 'pre-commit run --all'

repos:
- repo: https://gitlab.com/pycqa/flake8
  rev: '5.0.4'
  hooks:
  - id: flake8

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v0.971'
  hooks:
  - id: mypy
    files: jax/
    additional_dependencies: [types-requests==2.27.16, jaxlib==0.3.5]

- repo: https://github.com/mwouts/jupytext
  rev: v1.14.1
  hooks:
  - id: jupytext
    args: [--sync]
